version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with doc

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

# python:
#   install:
#     - method: poetry
#       path: .
#       extra_requirements:
#         - docs
#   system_packages: true
